name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and test
        shell: bash
        run: |
          rsync -av ./ /root/ros2_ws/src/last_updated/
          cd /root/ros2_ws
          . /opt/ros/humble/setup.bash
          colcon build
          ./src/last_updated/test/test.bash /root
